Fix crash where Kobweb server could fetch the wrong manifest file
... at which point it would NPE due to us force querying missing
properties.

To repro, before this fix...

* download the Jetbrains Runtime with JCEF installed
* set it as your Gradle runner (e.g. set JAVA_HOME)
* `kobweb run`

Result:

```
* What went wrong:
Execution failed for task ':site:kobwebStart'.
> Unable to start the Kobweb server.
  Error: Exception in thread "main" java.lang.NullPointerException
    at com.varabyte.kobweb.server.AppProperties$Companion.fromManifest(AppProperties.kt:19)
    at com.varabyte.kobweb.server.ApplicationKt.main(Application.kt:118)
    ...
    at com.varabyte.kobweb.server.ApplicationKt.main(Application.kt)
```

After this change, we now target OUR jar explicitly, so there's no
chance of getting the wrong manifest.

Fixes #745